# Custom Language File for Launcher Customizer

[ejs.app]
title = "돌순서버 런처"

[ejs.landing]
mediaLinkURL = "https://x.com/dolsun435964"
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/ujull1222/dolsun"
supportLink = "https://github.com/ujull1222/dolsun/issues"

[ejs.welcome]
welcomeHeader = "돌순 서버"
welcomeDescription = "마인크래프트 서버입니다! 해당 런처는 돌순서버만을 위해 제작되었습니다."
welcomeDescCTA = "즐겁게 플레이하시고 문제가 발생했을 시 디스코드로 문의 바랍니다"
